### ISSUE TITLE
Master tables V31 support?

### ISSUE THREAD

**Issue by stephaniemayfieldrwdi** [ywangd/pybufrkit#10]
Is version 31 of the master tables going to be added?  Or is there a way to take the tables as provided from WMO (http://www.wmo.int/pages/prog/www/WMOCodes/WMO306_vI2/LatestVERSION/LatestVERSION.html) and turn them into what is required?  I couldn't find any instructions on how to do that.

Thanks for the great tool!

Thanks
Steph

**Comment by ywangd** [comment]
Hi Steph, I just pushed a new commit to include both version 30 & 31 bufr tables. Also published the changes as a new version 0.2.7 to PyPI. Thanks for reporting.
