### ISSUE TITLE
Master version 34

### ISSUE THREAD

**Issue by stephaniemayfieldrwdi** [ywangd/pybufrkit#13]
Hello!  I was wondering when master version 34 will be supported. 

Thanks!

**Comment by ywangd** [comment]
Version 34 tables are now [added](https://github.com/ywangd/pybufrkit/commit/d198d5d4efa2b7c47e722b1bb7e5f4ea61cebb1c). A new release is now available on [PyPI](https://pypi.org/project/pybufrkit/).
