### ISSUE TITLE
Can't filter files

### ISSUE THREAD

**Issue by trrisner** [ywangd/pybufrkit#14]
pybufrkit decode -m --filter '${%data_category} == 2' FILE
does not work because filter is an unrecognized argument

**Comment by ywangd** [comment]
The `--filter` option is a new feature. Could you please ensure that you have the latest version (`0.2.17`) installed? The version can be checked with `pybufrkit --version`.

**Comment by trrisner** [comment]
it is 0.2.14. 
Thank You. 
Forgive my ignorance.
