### ISSUE TITLE
Master Table v36

### ISSUE THREAD

**Issue by stephaniemayfieldrwdi** [ywangd/pybufrkit#16]
WMO has released up to v36.  I was wondering if I can help with updating the master version?  I update our tables yearly in the summer.  I pull the tables from https://community.wmo.int/activity-areas/wmo-codes/manual-codes/latest-version.  Do you have a script to convert from the csv on that website to the json format you use?

**Comment by ywangd** [comment]
Added version 35 and 36 BUFR tables. They are converted from the BUFR4 files published at [WMO's GitHub repo](https://github.com/wmo-im/BUFR4).

Also added a [script](https://github.com/ywangd/pybufrkit/blob/master/pybufrkit/tablespreparer.py) that can be used to convert future table releases. You can run it as the follows:
```bash
python pybufrkit/tablespreparer.py 36
```
