### ISSUE TITLE
Decoding EUMETSAT AMV Bufr file

### ISSUE THREAD

**Issue by willcheng00** [ywangd/pybufrkit#22]
I used the command pybufrkit decode -j BUFR_FILE to decode an EUMETSAT AMV Bufr file.

The command works but the json files that comes out does not have a proper header.

I have a sample file here:

https://drive.google.com/file/d/1xf47kBRex-52AIvjah4azFOvptdOeLwb/view?usp=sharing

Thank you for any advice you can offer.

![Clipboard01](https://user-images.githubusercontent.com/67170852/195241216-3ca8b70b-c3a8-48a6-b151-5f6039d93149.jpg)

**Comment by ywangd** [comment]
I think you may want try `pybufrkit decode -ja BUFR_FILE`. Note the usage of `a` in the CLI options.

**Comment by willcheng00** [comment]
Thank you ywandgd! I get a more meaningful output

![Clipboard01](https://user-images.githubusercontent.com/67170852/195243392-1593cf6f-560a-4190-9d7a-3dc78f04998d.jpg)
