### ISSUE TITLE
Update to Tables V39

### ISSUE THREAD

**Issue by dspreitz** [ywangd/pybufrkit#25]
Hi ywangd,
could you pls update to V39 of the BUFR Table format?
V38 Tables are empty files.

BR,

Dominic

**Comment by ywangd** [comment]
Updated tables for both v38 and v39 with 14ba4f560a5708de10d8a377bc3c67b4b7fd8e59
A new 0.2.20 version is also published on PyPI.

**Comment by dspreitz** [comment]
Thanks a Lot for that!Am 18.02.2023 07:05 schrieb Yang Wang ***@***.***>:
Closed #25 as completed.
