### ISSUE TITLE
WMO : Update to V40 and V41

### ISSUE THREAD

**Issue by antoinemerle** [ywangd/pybufrkit#32]
# Context

I am thinking to use your library for decoding/encoding BUFR file from netCDF from the latest version table in order to use the latest sequence table d from version 41.

# Issue

I am not able to decode my file using the librairy because the following are not updated yet.
- Would it be possible to import `v40` and `v41` from WMO : latest version is now `41` : https://community.wmo.int/en/activity-areas/wis/latest-version ?
- How to import local table if not present ?

Thanks a million in advance.

**Comment by ywangd** [comment]
Sure I added a new release [v0.2.21](https://github.com/ywangd/pybufrkit/releases/tag/v0.2.21)
